- hosts: all
  become: yes
  tasks:
    - name: install kitty terminfo
      apt:
        name: kitty-terminfo
  roles:
    - role: dhcp
    - role: tftp
    - role: http
    - role: ipxe
    - role: harvester
